package com.dqj.knowledgenavi.dataobject;

public class UserInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.telephone
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_subject1
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userSubject1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject1_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject1_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject1Discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_subject2
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userSubject2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject2_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject2_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject2Discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_subject3
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userSubject3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject3_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject3_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject3Discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_subject4
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userSubject4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject4_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject4_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject4Discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_subject5
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String userSubject5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject5_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.subject5_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    private String subject5Discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.telephone
     *
     * @return the value of user_info.telephone
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.telephone
     *
     * @param telephone the value for user_info.telephone
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_subject1
     *
     * @return the value of user_info.user_subject1
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserSubject1() {
        return userSubject1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_subject1
     *
     * @param userSubject1 the value for user_info.user_subject1
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserSubject1(String userSubject1) {
        this.userSubject1 = userSubject1 == null ? null : userSubject1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject1_name
     *
     * @return the value of user_info.subject1_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject1Name() {
        return subject1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject1_name
     *
     * @param subject1Name the value for user_info.subject1_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject1Name(String subject1Name) {
        this.subject1Name = subject1Name == null ? null : subject1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject1_discription
     *
     * @return the value of user_info.subject1_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject1Discription() {
        return subject1Discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject1_discription
     *
     * @param subject1Discription the value for user_info.subject1_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject1Discription(String subject1Discription) {
        this.subject1Discription = subject1Discription == null ? null : subject1Discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_subject2
     *
     * @return the value of user_info.user_subject2
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserSubject2() {
        return userSubject2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_subject2
     *
     * @param userSubject2 the value for user_info.user_subject2
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserSubject2(String userSubject2) {
        this.userSubject2 = userSubject2 == null ? null : userSubject2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject2_name
     *
     * @return the value of user_info.subject2_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject2Name() {
        return subject2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject2_name
     *
     * @param subject2Name the value for user_info.subject2_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject2Name(String subject2Name) {
        this.subject2Name = subject2Name == null ? null : subject2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject2_discription
     *
     * @return the value of user_info.subject2_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject2Discription() {
        return subject2Discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject2_discription
     *
     * @param subject2Discription the value for user_info.subject2_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject2Discription(String subject2Discription) {
        this.subject2Discription = subject2Discription == null ? null : subject2Discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_subject3
     *
     * @return the value of user_info.user_subject3
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserSubject3() {
        return userSubject3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_subject3
     *
     * @param userSubject3 the value for user_info.user_subject3
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserSubject3(String userSubject3) {
        this.userSubject3 = userSubject3 == null ? null : userSubject3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject3_name
     *
     * @return the value of user_info.subject3_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject3Name() {
        return subject3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject3_name
     *
     * @param subject3Name the value for user_info.subject3_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject3Name(String subject3Name) {
        this.subject3Name = subject3Name == null ? null : subject3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject3_discription
     *
     * @return the value of user_info.subject3_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject3Discription() {
        return subject3Discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject3_discription
     *
     * @param subject3Discription the value for user_info.subject3_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject3Discription(String subject3Discription) {
        this.subject3Discription = subject3Discription == null ? null : subject3Discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_subject4
     *
     * @return the value of user_info.user_subject4
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserSubject4() {
        return userSubject4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_subject4
     *
     * @param userSubject4 the value for user_info.user_subject4
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserSubject4(String userSubject4) {
        this.userSubject4 = userSubject4 == null ? null : userSubject4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject4_name
     *
     * @return the value of user_info.subject4_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject4Name() {
        return subject4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject4_name
     *
     * @param subject4Name the value for user_info.subject4_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject4Name(String subject4Name) {
        this.subject4Name = subject4Name == null ? null : subject4Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject4_discription
     *
     * @return the value of user_info.subject4_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject4Discription() {
        return subject4Discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject4_discription
     *
     * @param subject4Discription the value for user_info.subject4_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject4Discription(String subject4Discription) {
        this.subject4Discription = subject4Discription == null ? null : subject4Discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_subject5
     *
     * @return the value of user_info.user_subject5
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getUserSubject5() {
        return userSubject5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_subject5
     *
     * @param userSubject5 the value for user_info.user_subject5
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setUserSubject5(String userSubject5) {
        this.userSubject5 = userSubject5 == null ? null : userSubject5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject5_name
     *
     * @return the value of user_info.subject5_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject5Name() {
        return subject5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject5_name
     *
     * @param subject5Name the value for user_info.subject5_name
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject5Name(String subject5Name) {
        this.subject5Name = subject5Name == null ? null : subject5Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.subject5_discription
     *
     * @return the value of user_info.subject5_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public String getSubject5Discription() {
        return subject5Discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.subject5_discription
     *
     * @param subject5Discription the value for user_info.subject5_discription
     *
     * @mbg.generated Wed Jan 06 20:05:52 CST 2021
     */
    public void setSubject5Discription(String subject5Discription) {
        this.subject5Discription = subject5Discription == null ? null : subject5Discription.trim();
    }
}