package com.dqj.knowledgenavi.dataobject;

public class UserPatentsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_patents.id
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_patents.class_code
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_patents.patent_name
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    private String patentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_patents.publication_no
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    private String publicationNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_patents.id
     *
     * @return the value of user_patents.id
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_patents.id
     *
     * @param id the value for user_patents.id
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_patents.class_code
     *
     * @return the value of user_patents.class_code
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_patents.class_code
     *
     * @param classCode the value for user_patents.class_code
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode == null ? null : classCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_patents.patent_name
     *
     * @return the value of user_patents.patent_name
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public String getPatentName() {
        return patentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_patents.patent_name
     *
     * @param patentName the value for user_patents.patent_name
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public void setPatentName(String patentName) {
        this.patentName = patentName == null ? null : patentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_patents.publication_no
     *
     * @return the value of user_patents.publication_no
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public String getPublicationNo() {
        return publicationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_patents.publication_no
     *
     * @param publicationNo the value for user_patents.publication_no
     *
     * @mbg.generated Wed Jan 06 13:45:20 CST 2021
     */
    public void setPublicationNo(String publicationNo) {
        this.publicationNo = publicationNo == null ? null : publicationNo.trim();
    }
}