package com.dqj.knowledgenavi.dataobject;

public class UserSubjectsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subjects.id
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subjects.class_name
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subjects.class_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    private String classCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subjects.parent_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    private String parentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subjects.id
     *
     * @return the value of user_subjects.id
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subjects.id
     *
     * @param id the value for user_subjects.id
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subjects.class_name
     *
     * @return the value of user_subjects.class_name
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subjects.class_name
     *
     * @param className the value for user_subjects.class_name
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subjects.class_code
     *
     * @return the value of user_subjects.class_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subjects.class_code
     *
     * @param classCode the value for user_subjects.class_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode == null ? null : classCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subjects.parent_code
     *
     * @return the value of user_subjects.parent_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subjects.parent_code
     *
     * @param parentCode the value for user_subjects.parent_code
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }
}