package com.dqj.knowledgenavi.dao;

import com.dqj.knowledgenavi.dataobject.UserSubjectsDO;

import java.util.List;

public interface UserSubjectsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    int insert(UserSubjectsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    int insertSelective(UserSubjectsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    UserSubjectsDO selectByPrimaryKey(Integer id);

    List<UserSubjectsDO> selectRecodesByPrefix(String lastFourTel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    int updateByPrimaryKeySelective(UserSubjectsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subjects
     *
     * @mbg.generated Mon Jan 04 20:29:40 CST 2021
     */
    int updateByPrimaryKey(UserSubjectsDO record);
}